### PR TITLE
Add cf-mgmt to the stack

### PR DESCRIPTION
**Pull request by combor**

### CODE REVIEW

**Comment by jimconner** [comment]
Why is this needed? We already have cf-mgmt in the ci-tools image which is the one used by the cf-utils pipeline for running the cf-mgmt jobs. Would be good to avoid duplicating the tools in multiple images unless strictly necessary.

**Comment by combor** [comment]
We have created this image to:
- reduce bandwith usage on our CI servers. As all the tools are here there is no need to download multiple different containers
- reduce disk space usage; we don't need to store multiple different containers on CI systems. Even with different tags of this container docker takes advantage of not re-downloading most of the image layers
- it's easier to manage in one place instead jumping between multiple-private and non-private repositories
- it's more secure; in case of security vulnarability in a tool we don;t have to update the entire flock of containers but just this one
- it's easier to update tools in one place, if we need to bump a tool version for some reason we update it here instead updating in 100 places
- it is automated on docker hub which is not true for all our containers
- it builds on tag push and doesn't build  "latest" so we don't break pipelines in an unpredictable way which is not true for all our containers

**Comment by combor** [comment]
Please check this story: https://jiraagile.bip.uk.fid-intl.com/browse/FILPAAS-3142

**Comment by jimconner** [comment]
The changes in this PR are not enough to mean that we could retire ci-tools container though. This one does not contain all of the same components at we use in ci-tools (see dockerfile at https://github.com/FidelityInternational/ci-tools/blob/master/Dockerfile ). 

Because the containers are for different jobs, we'd get no saving in disk space, we'd still have to manage both images (which are both public, on github and automated builds by dockerhub), and in the case of a security vulnerability we'd have to update both containers.

I'm not averse to having story played where we once again try to remove duplication in our docker containers and trim down the number of containers, but that story did not include creating a new container when the one that we had in-use already did everything that it needed to do.

**Comment by combor** [comment]
My intention was not to retire the tools container but retire it in specific jobs. It's easier to do it gradually as a boy scout job than play specific stories that we have to agree and schedule as this always competes with feature delivery stories.  As we are working on a story that changes jobs that use only `cf-mgmt` only and not other tools from ci-tools image we can easily change this one and retire ci-tools dukring the agreed story. It's gonna be less to change later.

**Comment by jimconner** [comment]
It is always the boyscout changes to our Dockerfiles which cause us unexpected problems down the line. I'm going to merge this now, and we'll see what breaks later.

**Pull request merged**
